spring:
  application:
    name: eureka-client
server:
  port: 0 # 0表示随机端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka
  instance:
    hostname: localhost