spring:
  application:
    name: eureka-consumer
server:
  port: 9999


provider:
  name: config-client

eureka:
  server: # 官方不存在的配置（自定义配置）
    host: 127.0.0.1
    port: 8762
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
    registryFetchIntervalSeconds: 5 # 5 秒轮训一次
  instance:
    instanceId: ${spring.application.name}:${server.port}


# Feign 客户端接口调用的日志
logging:
  level:
      com.zy.eureka.consumer.client.EurekServerProvider: DEBUG

#ribbon 超时重试配置
#ribbon:
#  MaxAutoRetries: 1 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
#  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
#  OkToRetryOnAllOperations: true
#  ReadTimeout: 1000
#  ConnectTimeout: 1000

#hystrix 超时配置
#hystrix:
#  command:
#    getName:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000

#feignClient 的超时fallback 配置
#feign:
#  hystrix:
#    enabled: true
#  client:
#      config:
#          default:
#              connectTimeout: 5000
#              readTimeout: 5000

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: full